# Generated by Django 4.2.1 on 2023-05-27 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shoppinglist_follow_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время не может быть менее 1 минуты')], verbose_name='Время приготовления, мин'),
        ),
    ]
